import type { Metadata } from "next";
import { Golos_Text } from "next/font/google"; 
import "./globals.css"; 

const golosText = Golos_Text({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/fonts/sf-pro-display.css" /> 
      </head>
      <body className={golosText.className}>
        {children}
      </body>
    </html>
  );
}
