import type { Metadata } from "next";
import { Golos_Text,Inter } from "next/font/google"; 
import "./globals.css"; 
const inter = Inter({
  subsets: ["latin"],

});
const golosText = Golos_Text({
  subsets: ["latin"],

});

export const metadata: Metadata = {
  title: "IT-park",
  description: "Generated by it-park",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <link rel="stylesheet" href="/fonts/sf-pro-display.css" /> 
        
      </head>
      <body className={`${inter.className} ${golosText.className}`}>
        {children}
      </body>
    </html>
  );
}
